image: debian:bookworm

stages:
  - build
  - deploy

before_script:
  - apt update && apt install -y doxygen graphviz cmake git

build-docs:
  stage: build
  script:
    - cmake -S . -B build
    - cmake --build build --target doc
    - mkdir -p public
    - cp -r build/docs/html/* public/
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
